version: "3.5"

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4242:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - .env

  mongodb:
    image: mongo
    hostname: mongo
    volumes:
      - ./data/mongodb:/data/db
    env_file:
      - .env
    restart: on-failure

  redis:
    image: redis
    ports:
      - 6379:6379
